# Generated by Django 4.0.5 on 2022-06-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
